---
title: 'Caso Hatco: Descripción'
author: "Jordi López Sintas"
date: "8 de enero de 2015"
output: pdf_document
---

#Los datos
La empresa Hatco ha pedido a un grupo sus clientes que valoren el producto que les ofrece. Para ello les ha preguntado su percepción acerca de siete atributos en los que ha descompuesto su oferta (numerados de 1 a 7 en la tabla siguiente); estos atributos son los que utilizan los clientes industriales a la hora de escoger a sus proveedores según la mayoría de estudios de marketing industrial realizados. Además, también ha recogido información acerca de la empresa encuestada que puede ser de utilidad para identificarlos, comprender sus percepciones y ayudarnos a preparar una estrategia comercial. La tabla 1 muestra la codificación de las variables  realizada de las respuestas a los cuestionarios de la muestra junto con su descripción y escala en la cual se han medido.

**Tabla 1**: codificación y significado de las bases de segmentación y de las  descriptivas

**Bases de segmentación**

1. X1="DELSPEED". Rapidez de entrega: Tiempo se tarda en servir un pedido una vez ha sido aceptado. Las siete primeras variables fueron medidas en una escala entre 0 (una valoración pobre) y 10 (una valoración excelente).

2. X2="PRICELEV". Nivel de precios: nivel de los precios cargados por los proveedores.

3. X3="PRICEFLE". Flexibilidad del nivel de precios: predisposición percibida de que los responsables comerciales de Hatco negocian el nivel del precio de todas las compras.

4. X4="MANUFIMA". Imagen que los clientes tienen del proveedor: Imagen global del proveedor.

5. X5="SERVICE". Servicio: Nivel global de servicio necesario para mantener una relación satisfactoria entre  proveedor y comprador (pre y postventa).

6. X6="SALESFOR". Imagen de la fuerza de ventas: Imagen global de la fuerza de ventas de Hatco, a mayor valoración, mayor puntuación.

7. X7="PRODUCTQ". Calidad de los productos: Nivel percibido de calidad de los productos.

**Variables descriptoras**
8. X8="TAMEMP". Tamaño de la empresa.

9. X9="USAGELEV". Nivel de uso: Qué porcentaje de las compras totales representan las realizadas a Hatco, su valor va desde 0 a 100%.

10. X10="SATISFLE". Nivel de satisfacción: Cuán satisfecho está el cliente con las compras realizadas a Hatco, medida en una escala entre 0 y 10.

11. X11="ESPCOMPR". Especificación de la compra: grado en el que un comprador evalúa cada compra de forma separada (analiza su valor total) frente a la utilización de especificaciones de compra, las cuales detallan las características del producto deseadas. Esta variable sólo puede tomar 2 valores: “total value analisis” (análisis del valor total que aporta la compra) o “specification buying” (compra según un pliego de especificaciones).

12. X12="ESTRCOMP". Estructura de la función de compra: método de aprovisionamiento en una empresa en particular. Esta variable toma dos valores, “Centralized procurement” (adquisición centralizada) o “decentralized produrement” (decisión de compra delegada).

13. X13="INDUSTRI". Tipo de industria: Clasificación industrial a la que pertenece la empresa compradora. Puede tomar dos valores, “industry A classification” o “other industries”.

14. X14= "SITCOMP".Tipo de situación de compra: Tipo de compra a la que se enfrenta el comprador. Esta variable puede tomar 3 valores, “new task” (compra de un nuevo producto), “modified rebuy” (compra anterior modificada) o  “straight rebuy” (compra rutinaria de anteriores productos).

**Nota**: las percepciones se han medido en una escala que oscila entre 0(una percepción mala) y10 (valoración excelente).

#El problema comercial de la empresa
La dirección de Hatco se propone averiguar si existen grupos de clientes con diferentes percepciones de su oferta con el objeto de diseñar una estrategia comercial específica para cada uno. De esta manera espera obtener un mayor rendimiento de sus gastos en marketing, mayores beneficios e incrementar su ventaja diferencial frente a sus competidores (suponiendo que estos tarden en reaccionar y la ventaja sea defendible)

Para poder interpretar mejor el resultado del análisis de clasificación de sus clientes, les ha pedido, también, que le den una valoración global de su satisfacción con la oferta de la empresa (variable X10="SATISFLE".) y del nivel de compras realizadas a Hatco durante un año, que se ha codificado en porcentaje: así un valor de 50 indica que del 50% de sus compras las realizan a nuestra empresa Hatco. Por ello la variable puede tomar valores entre 1, el menor volumen, y 100, máximo consumo, (variable X9="USAGELEV"). 

En el Anexo tenéis una guía de análisis con el programa de análisis de datos R. Es  tan sólo una guía que os ayudará a obtener una información significativa en la que, una vez valorada su calidad, podréis basar vuestras decisiones. No incluye el análisis discriminante, aunque quien lo desee puede utilizarlo si lo cree conveniente. (Para ello ya disponéis de dos guías de análisis para utilizarlo, una con dos segmentos y otra con cuatro.) Debéis decidir acerca de las bases de segmentación adecuadas: si éstas poseen las propiedades deseables para ser utilizadas en un trabajo de segmentación, y en caso de no poseerlas tenéis que realizar las transformación pertinentes de las bases de segmentación antes de utilizar los procedimientos de aglomeración (para analizar la heterogeneidad) y de partición (para asignar a cada individuo a un segmento determinado). Durante los procesos de clasificación utiliza una distancia euclidiana como medida de proximidad entre dos clientes, $d_{A,B}=\sqrt{(x_{1A}-x_{1B})^2+...+ (x_{pA}-x_{pB})^2}$ , y el algoritmo de Ward (o incremento mínimo en la variación total) en el proceso de aglomeración jerárquica. Para la partición utiliza el procedimiento kmeans.

#Preguntas para guiar el análisis

1.  ¿En qué casos podríamos utilizar las variables originales para realizar la agrupación  de los clientes con los procedimientos jerárquicos y no jerárquicos? ¿Se dan las condiciones en este ejemplo? ¿Por qué?
2.	¿En qué casos podríamos utilizar las variables estandarizadas o normalizadas para realizar la agrupación  de los clientes con los procedimientos jerárquicos y no jerárquicos? ¿Se dan las condiciones en este ejemplo? ¿Por qué?
3.	En función de los resultados que obtienes una vez decidas las transformaciones o no a realizar con las bases de segmentación, ¿cuántos grupos recomendarías? ¿Por qué?
4.	Con las variables adicionales y una vez identificados los segmentos y comprendido su comportamiento, ¿Podemos decir que tienen percepciones diferentes? ¿Qué relación tiene sus percepciones con el resto de las variables descriptivas ¿Con qué nombre los etiquetarías?
5.	¿Cómo adaptarías tu estrategia comercial ahora que sabes que existen dos grupos de clientes con percepciones diferentes, qué te sugiere la teoría del marketing? ¿Dejarías de servir un grupo y te concentrarías en el otro? ¿Utilizarías estrategias diferentes para cada grupos, en qué se diferenciarían?
6.	A la hora de poner en marcha tu estrategia comercial adaptada, ¿Encuentras a faltar alguna información que no se ha recogido en la investigación? ¿Es posible que la empresa ya disponga de ella? Qué indicios tienes. ¿De qué nos serviría?

    
